### ISSUE TITLE
Errors when run nosetests on local

### ISSUE THREAD

**Issue by litaotao** [jaysw/ipydb#11]
error info:

```
======================================================================
ERROR: tests.test_plugin.TestSqlPlugin.test_run_sql_script_interactive('a',)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Library/Python/2.7/site-packages/nose/case.py", line 197, in runTest
    self.test(*self.arg)
  File "/Users/chenshan/Desktop/github/ipydb/tests/test_plugin.py", line 76, in run_sql_check
    self.ip.run_sql_script('something', interactive=True)
  File "/Users/chenshan/Desktop/github/ipydb/ipydb/plugin.py", line 48, in wrapper
    return f(plugin, *args, **kw)
  File "/Users/chenshan/Desktop/github/ipydb/ipydb/plugin.py", line 346, in run_sql_script
    with open(script) as fin:
  File "/Library/Python/2.7/site-packages/mock/mock.py", line 1062, in __call__
    return _mock_self._mock_call(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mock/mock.py", line 1128, in _mock_call
    ret_val = effect(*args, **kwargs)
  File "/Library/Python/2.7/site-packages/mock/mock.py", line 2515, in reset_data
    if handle.readline.side_effect == _state[1]:
AttributeError: 'builtin_function_or_method' object has no attribute 'side_effect'
-------------------- >> begin captured stdout << ---------------------
ipydb is connecting to: mysql://barry:xxx@zing.com/db

--------------------- >> end captured stdout << ----------------------
```

code: 

```
class TestSqlPlugin(object):

    def setup(self):
        self.pmeta = mock.patch('ipydb.metadata.MetaDataAccessor')
        self.md_accessor = self.pmeta.start()
        self.mock_db = mock.MagicMock(spec=Database)
        self.md_accessor.get_metadata.return_value = self.mock_db
        self.pengine = mock.patch('ipydb.plugin.engine')
        self.mengine = self.pengine.start()
        configs = {
            'con1': {
                'type': 'mysql',
                'username': 'barry',
                'password': 'xyz',
                'host': 'zing',
                'database': 'db'
            }
        }
        self.mengine.getconfigs.return_value = ('con1', configs)
        self.mock_db_url = 'mysql://barry:xyz@zing.com/db'
        self.mengine.make_connection_url.return_value = self.mock_db_url
        self.sa_engine = mock.MagicMock()
        self.sa_engine.url.host = 'zing.com'
        self.sa_engine.url.database = 'db'
        self.mengine.from_url.return_value = self.sa_engine
        plugin.SqlPlugin.metadata_accessor = self.md_accessor
        self.ipython = mock.MagicMock(spec=TerminalInteractiveShell)
        self.ipython.config = None
        self.ipython.register_magics = mock.MagicMock()
        self.ipython.Completer = mock.MagicMock()
        self.ip = plugin.SqlPlugin(shell=self.ipython)
```

should I have a mysql server on local to run the tests? Or how to make it easy to run `nosetests` on local?

**Comment by jaysw** [comment]
Please merge with master.
